"""Added focus column

Revision ID: 1162f6919ce3
Revises: 78ebbbe49875
Create Date: 2020-07-02 09:07:03.081581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1162f6919ce3'
down_revision = '78ebbbe49875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spells', sa.Column('focus', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spells', 'focus')
    # ### end Alembic commands ###
