"""Create database

Revision ID: 78ebbbe49875
Revises: 
Create Date: 2020-07-01 15:07:00.437068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ebbbe49875'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_book', sa.String(), nullable=True),
    sa.Column('source_page', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('sub_school', sa.String(), nullable=True),
    sa.Column('descriptor', sa.String(), nullable=True),
    sa.Column('class_lvl', sa.String(), nullable=True),
    sa.Column('components', sa.String(), nullable=True),
    sa.Column('casting_time', sa.String(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('magic_targeting', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('saving_throw', sa.String(), nullable=True),
    sa.Column('resistance', sa.String(), nullable=True),
    sa.Column('descriptor_short', sa.String(), nullable=True),
    sa.Column('descriptor_long', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells')
    # ### end Alembic commands ###
